version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.6.4-stretch-node
    steps:
    - checkout
    - run:
        name: Which bundler?
        command: bundle -v
    - run:
        command: bundle install --path vendor/bundle
    # # Rubocop
    # - run:
    #     name: Rubocop
    #     command: bundle exec rubocop

workflows:
  version: 2
  workflow:
    jobs:
    - build
