default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: 'postgres'
  pool: 5

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  database: myapp_test
  
production:
  <<: *default
  host: excitemap-database.c3dwg1z8bl5l.ap-northeast-1.rds.amazonaws.com
  database: excitemap_database
  username: postgres
  password: 'postgres'

